Add check for changed files

diff --git a/.github/workflows/flyway-validate.yml b/.github/workflows/flyway-validate.yml
--- a/.github/workflows/flyway-validate.yml
+++ b/.github/workflows/flyway-validate.yml
@@ -4,14 +4,14 @@ on:
   pull_request:
     branches: [main]
 
-env:
-  FLYWAY_URL: jdbc:postgresql://postgres:5432/helios
-  FLYWAY_USER: helios
-  FLYWAY_PASSWORD: helios
-
 jobs:
   validate-migrations:
     runs-on: ubuntu-latest
+
+    env:
+      FLYWAY_URL: jdbc:postgresql://postgres:5432/helios
+      FLYWAY_USER: helios
+      FLYWAY_PASSWORD: helios
 
     services:
       postgres:
@@ -35,16 +35,40 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Check for changes
+        id: check_changes
+        run: |
+          CHANGED_PATHS=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -E "^server/application-server/src/main/resources/db/migration/")
+
+          if [[ -z "$CHANGED_PATHS" ]]; then
+            echo "CHANGE_DETECTED=false" >> "$GITHUB_OUTPUT"
+            echo "No Flyway migration changes detected."
+          else
+            echo "CHANGE_DETECTED=true" >> "$GITHUB_OUTPUT"
+            echo "Flyway migration changes detected in the following paths:"
+            echo "$CHANGED_PATHS"
+
+            if echo "$CHANGED_FILES" | grep -q "^M"; then
+              echo "Error: One or more existing migrations were changed."
+              exit 1
+            else
+              echo "No existing migrations were changed."
+            fi
+          fi
+
       - name: Set up Java
+        if: steps.check_changes.outputs.CHANGE_DETECTED == 'true'
         uses: actions/setup-java@v4
         with:
           distribution: "temurin"
           java-version: "21"
 
       - name: Run Gradle to apply Flyway migrations
+        if: steps.check_changes.outputs.CHANGE_DETECTED == 'true'
         working-directory: ./server/application-server
         run: ./gradlew flywayMigrate
 
       - name: Run Gradle to validate Flyway migrations
+        if: steps.check_changes.outputs.CHANGE_DETECTED == 'true'
         working-directory: ./server/application-server
         run: ./gradlew flywayValidate
