test: add server unit test setup

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,3 +31,43 @@ jobs:
           with:
               name: Coverage Report Client Tests
               path: client/coverage/lcov-report
+    server-tests:
+        runs-on: ubuntu-latest
+        timeout-minutes: 60
+        steps:
+        - uses: actions/checkout@v4
+        - name: Setup Java
+          uses: actions/setup-java@v4
+          with:
+            distribution: 'temurin'
+        - name: Server Tests
+          run: set -o pipefail && ./gradlew --console=plain test jacocoTestReport jacocoTestCoverageVerification | tee tests.log
+        - name: Print failed tests
+          if: failure()
+          run: grep "Test >.* FAILED\$" tests.log || echo "No failed tests."
+        - name: "Codacy: Report coverage"
+          uses: codacy/codacy-coverage-reporter-action@master
+          with:
+            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
+            coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
+          if: (github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name) && (success() || failure())
+        - name: Annotate Server Test Results
+          uses: ashley-taylor/junit-report-annotations-action@f9c1a5cbe28479439f82b80a5402a6d3aa1990ac
+          if: always()
+          with:
+            access-token: ${{ secrets.GITHUB_TOKEN }}
+            path: build/test-results/test/*.xml
+            numFailures: 99
+        - name: Test Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()    # run this step even if previous step failed
+          with:
+            name: H2 Tests
+            path: build/test-results/test/*.xml
+            reporter: java-junit
+        - name: Upload Server Test Coverage Report
+          if: success() || failure()
+          uses: actions/upload-artifact@v4
+          with:
+            name: Coverage Report Server Tests
+            path: build/reports/jacoco/test/html/
